function Features() {
  const features = [
    {
      icon: "🤖",
      title: "AI Generated Questions",
      description:
        "Real interview questions generated by Google Gemini AI based on your role and difficulty",
    },
    {
      icon: "🎤",
      title: "Voice Input",
      description:
        "Speak your answers just like a real interview using our built-in voice recognition",
    },
    {
      icon: "📊",
      title: "Instant Feedback",
      description:
        "Get detailed score and feedback from AI after every answer to improve faster",
    },
  ];

  return (
    <section className="features">
      <h2>Why Choose Our Platform?</h2>

      <p className="subtitle">
        Everything you need to crack your next interview
      </p>

      <div className="features-grid">
        {features.map((feature) => (
          <div className="feature-card" key={feature.title}>
            <div className="feature-icon">{feature.icon}</div>

            <h3>{feature.title}</h3>

            <p>{feature.description}</p>
          </div>
        ))}
      </div>
    </section>
  );
}

export default Features;